import { mkdir, writeFile } from 'fs/promises';
import path from 'path';

import type { TableMigrationConfig, TableFieldEntry, TableFieldMeta } from '../types';
import { collectRelations, type NormalizedRelation } from './relationUtils';
import { getParentModelValue, isSubTable } from './crudHelpers';

type DocOptions = {
  tables: TableMigrationConfig[];
  outputRoot: string;
};

type FieldInfo = {
  name: string;
  meta: TableFieldMeta;
};

const toPascal = (value: string) =>
  value
    .replace(/[^a-zA-Z0-9]+/g, ' ')
    .split(' ')
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');

const toCamel = (value: string) => {
  const pascal = toPascal(value);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
};

const decapitalize = (value: string) =>
  value ? value.charAt(0).toLowerCase() + value.slice(1) : value;

const buildDefaultRouterName = (table: TableMigrationConfig) => {
  const labelSource = table.name || table.table?.model || 'router';
  return decapitalize(toPascal(labelSource));
};

const getRouterKey = (table: TableMigrationConfig) => {
  if (table.router?.name) return table.router.name;
  const legacy = (table as any).trpc;
  if (legacy?.router) return legacy.router;
  return buildDefaultRouterName(table);
};

function collectFields(fields?: TableFieldEntry[]): FieldInfo[] {
  if (!fields) return [];
  const out: FieldInfo[] = [];
  for (const entry of fields) {
    for (const [name, meta] of Object.entries(entry)) {
      out.push({ name, meta });
    }
  }
  return out;
}

function formatList(items: string[]): string {
  if (!items.length) return 'None';
  return items.map((item) => `- ${item}`).join('\n');
}

function describeField(field: FieldInfo): string {
  const suffixes = [];
  if (field.meta.required) suffixes.push('required');
  if (field.meta.ignorePayload) suffixes.push('server-only');
  if (field.meta.transient) suffixes.push('transient');
  const suffix = suffixes.length ? ` (${suffixes.join(', ')})` : '';
  return `${field.name}${suffix}`;
}

function buildDoc(options: {
  table: TableMigrationConfig;
  routerKey: string;
  relationKeys: string[];
  taxonomyKeys: string[];
  subtableKeys: string[];
}): string {
  const { table, routerKey, relationKeys, taxonomyKeys, subtableKeys } = options;
  const modelName = table.name || table.table?.model || routerKey;
  const modelTitle = toPascal(modelName);
  const idType = table.id?.type ?? 'string';
  const parentModel = isSubTable(table) ? getParentModelValue(table) : null;

  const fields = collectFields(table.fields);
  const requiredFields = fields.filter(
    (field) => field.meta.required && !field.meta.ignorePayload
  );
  const requiredFieldList = requiredFields.map(describeField);

  const optionalFields = fields.filter(
    (field) => !field.meta.required && !field.meta.ignorePayload
  );
  const optionalFieldList = optionalFields.map(describeField);

  const resourceKeys = (table.resources ?? table.views ?? []).map((res) => res.name).filter(Boolean);
  const typesenseEnabled = Boolean(table.typesense);

  return `Title: ${modelTitle} Controller (Schema Kit)
Scope: schema-kit module
Applies to: Nuxt 4 + TRPC + SurrealDB

This document explains the **${modelTitle} controller** generated by Schema Kit.
It is intentionally explicit so an AI can follow it without confusion.

---

## 1) What this controller is

The **${modelTitle} controller** is a front-end helper that wraps the TRPC router for the \`${routerKey}\` model.
It gives you simple methods like \`create\`, \`update\`, \`delete\`, \`get\`, \`taxonomy\`, \`subtable\`, \`relation\`, and \`typesense\` (when enabled).

---

## 2) Where the controller lives

Generated base controller:
- \`module/src/runtime/controllers/generated/${routerKey}.ts\`

Wrapper that merges generated + custom overrides:
- \`module/src/runtime/controllers/${routerKey}.ts\`

Custom overrides (project side):
- \`schema/controllers/${routerKey}.ts\` (or \`app/schema/controllers/${routerKey}.ts\`)

---

## 3) How overrides work

The wrapper calls:
- \`createGenerated${modelTitle}Controller()\`
- \`extend${modelTitle}Controller\` (your custom overrides)

If a custom function has the **same name** as a generated function, the custom one **replaces** it.
If it’s a new function, it is added.

Example override:

\`\`\`ts
import type { ${modelTitle}Controller } from '@schema/controllers/${routerKey}'

export const extend${modelTitle}Controller = (base: ${modelTitle}Controller) => ({
  async update(id, payload, options) {
    return base.update(id, payload, options)
  },
  async customThing(id) {
    return base.get(id, 'Admin')
  },
})
\`\`\`

---

## 4) ID normalization (very important)

SurrealDB returns record ids as **objects** like:
\`\`\`ts
{ tb: '${table.table?.model ?? 'table'}', id: '123' }
\`\`\`

TRPC endpoints expect the **sub-id**, which for this model is:
\`${idType}\`

The controller accepts **either**:
- a record object
- a sub-id
- a full record object
- arrays/tuples of ids

It always normalizes to the sub-id before calling TRPC.

---

## 5) Create payload fields (model specific)

Required fields:
${formatList(requiredFieldList)}

Optional fields:
${formatList(optionalFieldList)}

---

## 6) Core Methods

### create(payload)
- TRPC endpoint: \`${routerKey}.create\`

### update(id, payload)
- TRPC endpoint: \`${routerKey}.update\`

### delete(id)
- TRPC endpoint: \`${routerKey}.delete\`

### get(id, resourceKey)
- TRPC endpoint: \`${routerKey}.resource\`
- Known resource keys: ${resourceKeys.length ? resourceKeys.join(', ') : 'None'}

---

## 7) Taxonomy Helper

Available taxonomies:
${formatList(taxonomyKeys)}

Endpoints:
- \`${routerKey}.<taxonomy>.createTaxonomy\`
- \`${routerKey}.<taxonomy>.addTerm\`
- \`${routerKey}.<taxonomy>.removeTerm\`
- \`${routerKey}.<taxonomy>.attach\`
- \`${routerKey}.<taxonomy>.detach\`
- \`${routerKey}.<taxonomy>.getTerms\`
- \`${routerKey}.<taxonomy>.getRecordTerms\`

---

## 8) Subtable Helper

Subtables under this model:
${formatList(subtableKeys)}

Endpoints:
- \`${routerKey}.subtables.<child>.create\`
- \`${routerKey}.subtables.<child>.update\`
- \`${routerKey}.subtables.<child>.delete\`
- \`${routerKey}.subtables.<child>.get\`
- \`${routerKey}.subtables.<child>.list\` (submany only)

This model is a subtable: ${parentModel ? `yes (parent model: ${parentModel})` : 'no'}

---

## 9) Relation Helper

Relations for this model:
${formatList(relationKeys)}

Endpoints:
- \`${routerKey}.relations.<relation>.attach\`
- \`${routerKey}.relations.<relation>.detach\`
- \`${routerKey}.relations.<relation>.list\`

---

## 10) Typesense Helper

Typesense enabled: ${typesenseEnabled ? 'yes' : 'no'}

Endpoints (if enabled):
- \`${routerKey}.typesense.resource\`
- \`${routerKey}.typesense.list\`
- \`${routerKey}.typesense.refresh\`
- \`${routerKey}.typesense.count\`
- \`${routerKey}.typesense.collection\`

---

## 11) TRPC Router Location

Generated router:
- \`server/trpc/routers/generated/${routerKey}.ts\`

Wrapper router:
- \`server/trpc/routers/${routerKey}.ts\`

---

End of document.
`;
}

export async function generateControllerDocs(options: DocOptions): Promise<void> {
  const { tables, outputRoot } = options;
  await mkdir(outputRoot, { recursive: true });

  const relations = collectRelations(tables);
  const relationsByModel = new Map<string, NormalizedRelation[]>();
  for (const rel of relations) {
    const left = relationsByModel.get(rel.leftModel) ?? [];
    left.push(rel);
    relationsByModel.set(rel.leftModel, left);
    const right = relationsByModel.get(rel.rightModel) ?? [];
    right.push(rel);
    relationsByModel.set(rel.rightModel, right);
  }

  const subtablesByParent = new Map<string, TableMigrationConfig[]>();
  for (const table of tables) {
    if (!isSubTable(table)) continue;
    const parentModel = getParentModelValue(table);
    if (!parentModel) continue;
    const list = subtablesByParent.get(parentModel) ?? [];
    list.push(table);
    subtablesByParent.set(parentModel, list);
  }

  for (const table of tables) {
    const routerKey = getRouterKey(table);
    const taxonomies = (table.taxonomies ?? []).map((item) => item.key).filter(Boolean);
    const related = relationsByModel.get(table.table?.model ?? '') ?? [];
    const relationKeys = related.map((rel) => {
      const isLeft = rel.leftModel === (table.table?.model ?? '');
      const other = isLeft ? rel.rightLabel : rel.leftLabel;
      return toCamel(other);
    });
    const subtableChildren = subtablesByParent.get(table.table?.model ?? '') ?? [];
    const subtableKeys = subtableChildren.map((child) => getRouterKey(child));

    const content = buildDoc({
      table,
      routerKey,
      relationKeys,
      taxonomyKeys: taxonomies,
      subtableKeys,
    });

    const outputPath = path.join(outputRoot, `${routerKey}.md`);
    await writeFile(outputPath, content, 'utf-8');
  }
}
