import { mkdir, writeFile } from 'fs/promises';
import path from 'path';

import type { AppConfig, RequestSchemaConfig } from '../types';

interface GenerateRequestSchemaOptions {
  app: AppConfig;
  projectRoot: string;
  outputPath?: string;
}

export async function generateRequestSchema(
  options: GenerateRequestSchemaOptions
): Promise<void> {
  const { app, projectRoot, outputPath: overrideOutput } = options;
  const cfg = app.requestSchema ?? {};

  const defaultOutput = path.resolve(
    projectRoot,
    '../../packages/pmv2shared/trpc/request-schema.ts'
  );
  const outputPath =
    overrideOutput ??
    (cfg.output
      ? path.isAbsolute(cfg.output)
        ? cfg.output
        : path.resolve(projectRoot, cfg.output)
      : defaultOutput);

  const instances = resolveInstances(app, cfg);
  const content = buildRequestSchemaFile(instances);

  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, content, 'utf-8');

  console.log(`🧩 Generated RequestSchema: ${path.relative(projectRoot, outputPath)}`);
}

function resolveInstances(app: AppConfig, cfg: RequestSchemaConfig): string[] {
  if (Array.isArray(cfg.instances) && cfg.instances.length > 0) {
    return cfg.instances;
  }

  const entries = Object.entries(app.databases ?? {});
  const includeInactive = cfg.includeInactive === true;
  const resolved = entries
    .filter(([, db]) => includeInactive || db.active !== false)
    .map(([key]) => key);

  return resolved.length > 0 ? resolved : ['default'];
}

function buildRequestSchemaFile(instances: string[]): string {
  const enumValues = instances.map((name) => JSON.stringify(name)).join(', ');

  return [
    `import { z } from 'zod'`,
    '',
    `// Auto-generated by passmed-schema. Do not edit manually.`,
    `export const InstanceCode_z = z.enum([${enumValues}])`,
    `export type InstanceCode = z.infer<typeof InstanceCode_z>`,
    '',
    `// Overload without extras`,
    `export function RequestSchema<Data extends z.ZodTypeAny>(dataSchema: Data): z.ZodObject<{ data: Data; instance?: typeof InstanceCode_z }>`,
    '',
    `// Overload with extras`,
    `export function RequestSchema<Data extends z.ZodTypeAny, Extras extends Record<string, z.ZodTypeAny>>(`,
    `  dataSchema: Data,`,
    `  options: Extras,`,
    `): z.ZodObject<{ data: Data; instance?: typeof InstanceCode_z } & Extras>`,
    '',
    `// Implementation`,
    `export function RequestSchema<Data extends z.ZodTypeAny, Extras extends Record<string, z.ZodTypeAny>>(`,
    `  dataSchema: Data,`,
    `  options?: Extras,`,
    `): z.ZodObject<{ data: Data; instance?: typeof InstanceCode_z } & Extras> {`,
    `  const safeSchema = dataSchema && typeof (dataSchema as any).safeParse === 'function'`,
    `    ? dataSchema`,
    `    : z.any()`,
    `  const baseShape: Record<string, z.ZodTypeAny> = {`,
    `    data: safeSchema,`,
    `    instance: InstanceCode_z.optional(),`,
    `  }`,
    '',
    `  if (options) {`,
    `    return z.object({ ...baseShape, ...options }) as z.ZodObject<{ data: Data } & Extras>`,
    `  }`,
    '',
    `  return z.object(baseShape) as z.ZodObject<{ data: Data } & Extras>`,
    `}`,
    '',
    `export type InferRequestSchema<T extends ReturnType<typeof RequestSchema>> = z.infer<T>`,
    '',
  ].join('\n');
}
