import path from 'path';
import { writeFile } from 'fs/promises';

export async function writeGeneratedNuxtConfig(
  appRoot: string,
  config: Record<string, unknown> | undefined
): Promise<void> {
  const filePath = path.join(appRoot, 'nuxt.config.generated.ts');
  const baseConfig: Record<string, unknown> = config ? { ...config } : {};
  if (baseConfig.compatibilityDate === undefined) {
    baseConfig.compatibilityDate = '2026-01-30';
  }
  const normalized = normalizeConfigValue(baseConfig);
  const body = formatJsValue(normalized, 0);
  const output = `// Generated by schema site tooling. Do not edit directly.\nexport default ${body};\n`;
  await writeFile(filePath, output, 'utf-8');
}

function formatJsValue(value: unknown, indent: number): string {
  if (Array.isArray(value)) {
    return formatArray(value, indent);
  }
  if (value === null) return 'null';
  if (typeof value === 'string') return JSON.stringify(value);
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  if (value && typeof value === 'object') {
    return formatObject(value as Record<string, unknown>, indent);
  }
  return 'undefined';
}

function formatArray(values: unknown[], indent: number): string {
  if (values.length === 0) return '[]';
  const nextIndent = indent + 2;
  const lines = values.map((item) => `${' '.repeat(nextIndent)}${formatJsValue(item, nextIndent)}`);
  return `[\n${lines.join(',\n')}\n${' '.repeat(indent)}]`;
}

function formatObject(value: Record<string, unknown>, indent: number): string {
  const entries = Object.entries(value);
  if (entries.length === 0) return '{}';
  const nextIndent = indent + 2;
  const lines = entries.map(([key, val]) => {
    const formattedKey = isValidIdentifier(key) ? key : JSON.stringify(key);
    return `${' '.repeat(nextIndent)}${formattedKey}: ${formatJsValue(val, nextIndent)}`;
  });
  return `{\n${lines.join(',\n')}\n${' '.repeat(indent)}}`;
}

function isValidIdentifier(key: string): boolean {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key);
}

export function normalizeConfigValue(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map((item) => normalizeConfigValue(item)).filter((item) => item !== undefined);
  }
  if (value && typeof value === 'object') {
    const out: Record<string, unknown> = {};
    for (const [key, val] of Object.entries(value as Record<string, unknown>)) {
      const normalized = normalizeConfigValue(val);
      if (normalized !== undefined) {
        out[key] = normalized;
      }
    }
    return out;
  }
  if (value === undefined) return undefined;
  return value;
}
