import path from 'path';
import { writeFile } from 'fs/promises';

export async function writeGeneratedNuxtConfig(
  appRoot: string,
  config: Record<string, unknown> | undefined
): Promise<void> {
  const filePath = path.join(appRoot, 'nuxt.config.generated.ts');
  const baseConfig: Record<string, unknown> = config ? { ...config } : {};
  if (baseConfig.compatibilityDate === undefined) {
    baseConfig.compatibilityDate = '2026-01-30';
  }
  const normalized = normalizeConfigValue(baseConfig);
  const body = JSON.stringify(normalized, null, 2);
  const output = `// Generated by schema site tooling. Do not edit directly.\nexport default ${body};\n`;
  await writeFile(filePath, output, 'utf-8');
}

export function normalizeConfigValue(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map((item) => normalizeConfigValue(item)).filter((item) => item !== undefined);
  }
  if (value && typeof value === 'object') {
    const out: Record<string, unknown> = {};
    for (const [key, val] of Object.entries(value as Record<string, unknown>)) {
      const normalized = normalizeConfigValue(val);
      if (normalized !== undefined) {
        out[key] = normalized;
      }
    }
    return out;
  }
  if (value === undefined) return undefined;
  return value;
}
