import { mkdir, readFile, writeFile } from 'fs/promises';
import path from 'path';

import type { AppConfig, AppDatabaseConfig, SurrealMcpExportConfig } from '../types';

interface GenerateSurrealMcpExportOptions {
  app: AppConfig;
  projectRoot: string;
  databaseKey?: string;
  outputPath?: string;
  codexConfigOutputPath?: string;
  port?: number;
  serverName?: string;
  serviceName?: string;
  containerName?: string;
  approvalMode?: string;
}

const TOML_BEGIN = '# BEGIN schema-tools surrealmcp generated';
const TOML_END = '# END schema-tools surrealmcp generated';

export async function generateSurrealMcpExport(
  options: GenerateSurrealMcpExportOptions,
): Promise<void> {
  const { app, projectRoot } = options;
  const cfg = app.surrealMcpExport ?? {};
  const repoRoot = path.resolve(projectRoot, '..');
  const databaseKey =
    normalizeString(options.databaseKey) ||
    normalizeString(cfg.database) ||
    normalizeString(app.environment?.defaultDatabase);

  if (!databaseKey) {
    throw new Error('surrealMcpExport requires a database key or environment.defaultDatabase.');
  }

  const databaseConfig = app.databases?.[databaseKey];
  if (!databaseConfig) {
    throw new Error(`surrealMcpExport references undefined database "${databaseKey}".`);
  }

  const port = resolvePort(options.port, cfg.port);
  const serverName = normalizeString(options.serverName) || normalizeString(cfg.serverName) || `surreal${port}`;
  const serviceName = normalizeString(options.serviceName) || normalizeString(cfg.serviceName) || 'surrealmcp';
  const containerName =
    normalizeString(options.containerName) || normalizeString(cfg.containerName) || `${serviceName}_${port}`;
  const approvalMode =
    normalizeString(options.approvalMode) || normalizeString(cfg.approvalMode) || 'approve';
  const composeOutputPath = resolveOutputPath(
    projectRoot,
    repoRoot,
    options.outputPath,
    cfg.output,
    'surrealmcp.compose.yml',
  );
  const codexConfigOutputPath = resolveOutputPath(
    projectRoot,
    repoRoot,
    options.codexConfigOutputPath,
    cfg.codexConfigOutput,
    path.join('.codex', 'config.toml'),
  );

  const composeContent = buildComposeFile({
    databaseKey,
    databaseConfig,
    port,
    serviceName,
    containerName,
    dockerHost: normalizeString(cfg.dockerHost) || 'host.docker.internal',
  });

  await mkdir(path.dirname(composeOutputPath), { recursive: true });
  await writeFile(composeOutputPath, composeContent, 'utf-8');
  console.log(`🧩 Generated Surreal MCP compose: ${path.relative(repoRoot, composeOutputPath)}`);

  const codexContent = await buildCodexConfig({
    filePath: codexConfigOutputPath,
    databaseKey,
    port,
    serverName,
    enabled: cfg.enabled !== false,
    approvalMode,
  });
  await mkdir(path.dirname(codexConfigOutputPath), { recursive: true });
  await writeFile(codexConfigOutputPath, codexContent, 'utf-8');
  console.log(`🧩 Synced Codex MCP config: ${path.relative(repoRoot, codexConfigOutputPath)}`);
}

function buildComposeFile(input: {
  databaseKey: string;
  databaseConfig: AppDatabaseConfig;
  port: number;
  serviceName: string;
  containerName: string;
  dockerHost: string;
}): string {
  const endpoint = buildSurrealRpcEndpoint(input.databaseConfig.url, input.dockerHost);
  return [
    `# AUTO-GENERATED by schema-tools surrealmcp:generate from apps/schema/config/app.config.yaml`,
    `# Source database: ${input.databaseKey}`,
    `services:`,
    `  ${input.serviceName}:`,
    `    image: surrealdb/surrealmcp:latest`,
    `    container_name: ${input.containerName}`,
    `    restart: unless-stopped`,
    `    command: >`,
    `      start`,
    `      --bind-address 0.0.0.0:${input.port}`,
    `      --server-url http://localhost:${input.port}`,
    `      --endpoint ${endpoint}`,
    `      --ns ${input.databaseConfig.namespace}`,
    `      --db ${input.databaseConfig.database}`,
    `      --user ${input.databaseConfig.username}`,
    `      --pass ${input.databaseConfig.password}`,
    `      --auth-disabled`,
    `    ports:`,
    `      - "${input.port}:${input.port}"`,
    ``,
  ].join('\n');
}

async function buildCodexConfig(input: {
  filePath: string;
  databaseKey: string;
  port: number;
  serverName: string;
  enabled: boolean;
  approvalMode: string;
}): Promise<string> {
  const nextBlock = [
    TOML_BEGIN,
    `# Repo-local Surreal MCP proxy backed by the \`${input.databaseKey}\` database config in`,
    `# \`apps/schema/config/app.config.yaml\`, exposed locally at port ${input.port}.`,
    `[mcp_servers.${input.serverName}]`,
    `url = ${JSON.stringify(`http://localhost:${input.port}/mcp`)}`,
    `enabled = ${input.enabled ? 'true' : 'false'}`,
    ``,
    `[mcp_servers.${input.serverName}.tools.connect_endpoint]`,
    `approval_mode = ${JSON.stringify(input.approvalMode)}`,
    TOML_END,
    ``,
  ].join('\n');

  let existing = '';
  try {
    existing = await readFile(input.filePath, 'utf-8');
  } catch (error: any) {
    if (error?.code !== 'ENOENT') throw error;
  }

  if (!existing.trim()) return nextBlock;

  const blockPattern = new RegExp(
    `${escapeRegExp(TOML_BEGIN)}[\\s\\S]*?${escapeRegExp(TOML_END)}\\n?`,
    'm',
  );

  const managedMatch = blockPattern.exec(existing);
  if (managedMatch) {
    const before = existing.slice(0, managedMatch.index);
    const after = existing.slice(managedMatch.index + managedMatch[0].length);
    const keepBefore = before
      .split('\n')
      .some((line) => {
        const trimmed = line.trim();
        return trimmed && !trimmed.startsWith('#');
      });
    const merged = `${keepBefore ? before.trimEnd() + '\n\n' : ''}${nextBlock}${after.trimStart()}`;
    return merged.replace(/\n{3,}/g, '\n\n').trimEnd() + '\n';
  }

  const stripped = stripLegacyServerSections(existing, input.serverName).trimEnd();
  if (!stripped) return nextBlock;
  return `${stripped}\n\n${nextBlock}`;
}

function resolveOutputPath(
  projectRoot: string,
  repoRoot: string,
  overrideOutput: string | undefined,
  configOutput: string | undefined,
  defaultRelativeToRepoRoot: string,
): string {
  if (overrideOutput) {
    return path.isAbsolute(overrideOutput)
      ? overrideOutput
      : path.resolve(projectRoot, overrideOutput);
  }

  if (configOutput) {
    return path.isAbsolute(configOutput)
      ? configOutput
      : path.resolve(repoRoot, configOutput);
  }

  return path.resolve(repoRoot, defaultRelativeToRepoRoot);
}

function buildSurrealRpcEndpoint(url: string, dockerHost: string): string {
  const parsed = new URL(url);
  if (parsed.protocol === 'http:') parsed.protocol = 'ws:';
  else if (parsed.protocol === 'https:') parsed.protocol = 'wss:';
  else if (parsed.protocol !== 'ws:' && parsed.protocol !== 'wss:') {
    throw new Error(`Unsupported SurrealDB URL protocol for MCP export: ${parsed.protocol}`);
  }

  if (['127.0.0.1', 'localhost', '0.0.0.0'].includes(parsed.hostname)) {
    parsed.hostname = dockerHost;
  }

  if (!parsed.pathname || parsed.pathname === '/') {
    parsed.pathname = '/rpc';
  }

  return parsed.toString().replace(/\/$/, '');
}

function resolvePort(...values: Array<number | undefined>): number {
  for (const value of values) {
    if (typeof value === 'number' && Number.isFinite(value) && value > 0) {
      return Math.round(value);
    }
  }
  return 911;
}

function normalizeString(value: string | undefined | null): string {
  return String(value ?? '').trim();
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function stripLegacyServerSections(content: string, serverName: string): string {
  const lines = content.split('\n');
  const next: string[] = [];
  const prefix = `[mcp_servers.${serverName}`;
  let skipping = false;

  for (const line of lines) {
    const trimmed = line.trim();
    const isHeader = trimmed.startsWith('[') && trimmed.endsWith(']');

    if (isHeader) {
      if (trimmed === `[mcp_servers.${serverName}]` || trimmed.startsWith(`${prefix}.`)) {
        while (next.length > 0) {
          const previous = next[next.length - 1]?.trim() ?? '';
          if (!previous || previous.startsWith('#')) {
            next.pop();
            continue;
          }
          break;
        }
        skipping = true;
        continue;
      }
      if (skipping) {
        skipping = false;
      }
    }

    if (!skipping) {
      next.push(line);
    }
  }

  return next.join('\n').replace(/\n{3,}/g, '\n\n');
}
