version: 1
kind: table
name: QuestionAttempt
primary: true
tableType: primary
description: Question attempts (core analytic primitive)
table:
  model: qa
  type: NORMAL
  schemaMode: schemaless
  permissions: full
id:
  type: string
  exportType: true
  exportName: QuestionAttemptId
modelSettings:
  authority: tenant
fields:
  - s:
      type: record<s>
      default: ""
      assign: true
  - q:
      type: record<q>
      required: true
      default: ""
      assign: true
  - u:
      type: record<u>
      required: true
      default: ""
      assign: true
  - selectedOptionID:
      type: record<qo>
      required: true
      default: ""
      assign: true
  - correct:
      type: boolean
      default: false
  - order:
      type: number
      default: 0
  - startTS:
      type: datetime
      default: ""
      ignorePayload: true
  - answerTS:
      type: datetime
      default: ""
      ignorePayload: true
  - totalTime:
      type: number
      default: 0
  - create_at:
      type: datetime
      default: ""
      ignorePayload: true
  - exams:
      type: array<record<exam>>
      default: []
  - examsTerms:
      type: array<object>
      default: []
  - categories:
      type: "array<{ id: record<exam>, categories: record<qt>[] }>"
      default: []
  - categoryIds:
      type: array<record<qt>>
      default: []
  - _reconciliationKey:
      type: string
      default: ""
      ignorePayload: true
crud:
  create:
    enabled: true
    name: create__NAME__
    params:
      - name: payload
        type: object
  update:
    enabled: true
    name: update__NAME__
    params:
      - name: rid
        type: record
      - name: payload
        type: object
  delete:
    enabled: true
    name: delete__NAME__
    params:
      - name: rid
        type: record
router:
  name: questionAttempt
  endpoints:
    - create
    - update
    - delete
relations:
  - edge: UserAttempts
    left: u
    right: qa
    cardinality: many
    storeOnModel: true
    payloadField: u
    linkOnCreate: true
    required: false
    processor: functions
    hook: right
  - edge: QuestionAttempts
    left: q
    right: qa
    cardinality: many
    storeOnModel: true
    payloadField: q
    linkOnCreate: true
    required: false
    processor: functions
    hook: right
  - edge: SessionAttempts
    left: s
    right: qa
    cardinality: many
    storeOnModel: true
    payloadField: s
    linkOnCreate: true
    required: false
    processor: functions
    hook: right
  - edge: ExamAttempts
    left: exam
    right: qa
    cardinality: many
    storeOnModel: true
    payloadField: exams
    linkOnCreate: true
    required: false
    processor: functions
    hook: right
  - edge: TermAttempts
    left: qt
    right: qa
    cardinality: many
    storeOnModel: true
    payloadField: categoryIds
    linkOnCreate: true
    required: false
    processor: functions
    hook: right
refreshViews: true
admin:
  authority: tenant
  data: tenant
