version: 1
kind: table
name: ProductVariant
primary: false
tableType: submany
description: Price variant (period + currency)
table:
  model: productVariant
  type: NORMAL
  schemaMode: schemaless
  permissions: full
id:
  type: string
  exportType: true
  exportName: ProductVariantId
  structure: stringID<productKey, period, currency>
fields:
  - productKey:
      type: string
      required: true
      default: ""
  - examKey:
      type: string
      required: true
      default: ""
  - product:
      type: record<product>
      required: true
      default: ""
      assign: true
  - exam:
      type: record<exam>
      required: true
      default: ""
      assign: true
  - period:
      type: int
      required: true
      default: 0
  - currency:
      type: record<currency>
      required: true
      default: ""
      assign: true
  - value:
      type: number
      required: true
      default: 0
  - label:
      type: string
      default: ""
  - stripePriceID:
      type: string
      default: ""
  - order:
      type: number
      default: 0
edges:
  has: []
  belongs:
    - table: ProductVariant
      in: product
      out: productVariant
    - table: ProductVariants
      in: product
      out: productVariant
      unique: true
crud:
  create:
    enabled: true
    name: create__NAME__
    params:
      - name: payload
        type: object
  update:
    enabled: true
    name: update__NAME__
    params:
      - name: rid
        type: record
      - name: payload
        type: object
  delete:
    enabled: true
    name: delete__NAME__
    params:
      - name: rid
        type: record
router:
  name: productVariant
  parent: product
  endpoints:
    - create
    - update
    - delete
relations:
  - edge: VariantExtensionProduct
    left: productVariant
    right: extensionProduct
    cardinality: one
    storeOnModel: false
    payloadField: extensionProduct
    linkOnCreate: true
    required: false
    processor: functions
    hook: right
refreshViews: true
