services:
  surrealmcp_prod_v1:
    image: surrealdb/surrealmcp:latest
    container_name: surrealmcp_prod_v1
    restart: unless-stopped
    command: >
      start
      --bind-address 0.0.0.0:10911
      --server-url http://localhost:10911
      --endpoint wss://api.luckyisibaya.co.za/rpc
      --ns appns
      --db app_v1
      --user mpire
      --pass BurntMyMoustacheIn1986
      --auth-disabled
    ports:
      - "10911:10911"
