version: 1
kind: table
name: Question
primary: true
tableType: primary
description: A basic question table
table:
  model: q
  type: NORMAL
  schemaMode: schemaless
  permissions: full
id:
  type: string
  structure: qid
  exportType: true
  exportName: QuestionId
fields:
  - qid:
      type: number
      required: true
      default: 0
  - qCode:
      type: string
      default: ""
  - question:
      type: string
      required: true
      default: ""
  - explanation:
      type: string
      default: ""
  - explanationRef:
      type: string
      default: ""
  - source:
      type: string
      default: ""
  - instances:
      type: array<string>
      required: true
      default: []
  - testobject:
      type: object
      fields:
        testobjectnumber:
          type: number
          required: true
          default: 0
        testobjectstring:
          type: string
          default: ""
        testobjectdarray:
          type: array<string>
          default: []
        testobjectobject:
          type: object
          fields:
            testobjectobjectnumber:
              type: number
              required: true
              default: 0
            testobjectobjectstring:
              type: string
              default: ""
            testobjectobjectarray:
              type: array<string>
              default: []
  - tags:
      type: array<record<term>>
subTables:
  - name: QuestionRecord
    model: qRecord
    autoCreate: true
    tableType: subsingle
  - name: QuestionOption
    model: qOption
    autoCreate: false
    tableType: submany
crud:
  create:
    enabled: true
    name: create__NAME__
    params:
      - name: payload
        type: object
  update:
    enabled: true
    name: update__NAME__
    params:
      - name: rid
        type: record
      - name: payload
        type: object
  delete:
    enabled: true
    name: delete__NAME__
    params:
      - name: rid
        type: record
router:
  name: question
  endpoints:
    - create
    - update
    - delete
    - views: "*"
views:
  - name: Admin
    fields:
      - id
      - qid
      - qCode
      - question
      - explanation
      - explanationRef
      - source
      - instances
      - testobject
    functionMode: generate
    function: viewQuestionAdmin
taxonomies:
  - key: qcat
    labels:
      singular: Category
      plural: Categories
    taxonomy:
      id: stringID<q, qcat>
      fields:
        - key:
            type: string
            required: true
        - label:
            type: string
            required: true
        - hierarchical:
            type: boolean
            required: false
            default: false
        - permalink:
            type: <permalink<<field:key>>>
            required: false
            assign: true
        - description: Question categories
    term:
      id: <field:key>
      fields:
        - key:
            type: string
            required: true
        - label:
            type: string
            required: true
        - description:
            type: string
            required: false
        - parent:
            type: record<term>
            required: false
            default: ""
    hierarchical: true
    storeOnModel: false
    payloadField: categories
    processor: functions
  - key: qtag
    labels:
      singular: Tag
      plural: Tags
    taxonomy:
      id: stringID<q, qtag>
      fields:
        - key:
            type: string
            required: true
        - label:
            type: string
            required: true
        - hierarchical:
            type: boolean
            required: false
            default: false
        - permalink:
            type: <permalink<<field:key>>>
            required: false
            assign: true
        - description: Question tags
    term:
      id: <field:key>
      fields:
        - key:
            type: string
            required: true
        - label:
            type: string
            required: true
        - description:
            type: string
            required: false
        - parent:
            type: record<term>
            required: false
            default: ""
    hierarchical: false
    storeOnModel: true
    payloadField: tags
    processor: functions
instance: true
post: true
refreshViews: true
admin:
  data: local
