version: 1
kind: table
name: QuestionNote
primary: false
tableType: submany
description: Administrative admin notes for questions
table:
  model: qnote
  type: NORMAL
  schemaMode: schemaless
  permissions: full
id:
  type: string
  exportType: true
  exportName: QuestionNoteId
structure:
  type: parent
  parentModel: q
fields:
  - q:
      type: record<q>
      required: true
      default: ""
      assign: true
  - note:
      type: string
      default: ""
  - order:
      type: number
      default: 0
  - createdAt:
      type: datetime
      required: true
      default: time::now()
  - createdBy:
      type: record<u>
      required: true
      default: ""
      assign: true
  - createdByName:
      type: string
      required: true
      default: ""
  - updatedAt:
      type: datetime
      default: ""
      ignorePayload: true
  - updatedBy:
      type: record<u>
      default: ""
      ignorePayload: true
edges:
  has: []
  belongs:
    - table: QuestionNote
      in: q
      out: qnote
crud:
  create:
    enabled: true
    name: create__NAME__
    params:
      - name: payload
        type: object
  update:
    enabled: true
    name: update__NAME__
    params:
      - name: rid
        type: record
      - name: payload
        type: object
  delete:
    enabled: true
    name: delete__NAME__
    params:
      - name: rid
        type: record
router:
  name: questionNote
  parent: q
  endpoints:
    - create
    - update
    - delete
refreshViews: true
