version: 1
kind: table
name: QuestionPerformanceRecord
primary: false
tableType: subsingle
description: Aggregate performance for this question
table:
  model: qpr
  type: NORMAL
  schemaMode: schemaless
  permissions: full
id:
  type: string
  exportType: true
  exportName: QuestionPerformanceRecordId
structure:
  type: parent
  parentModel: q
fields:
  - attempts:
      type: number
      default: 0
  - noCorrect:
      type: number
      default: 0
  - noIncorrect:
      type: number
      default: 0
  - percCorrect:
      type: number
      default: 0
  - totalTime:
      type: number
      default: 0
  - averageTime:
      type: number
      default: 0
edges:
  has: []
  belongs:
    - table: QuestionPerformanceRecord
      in: q
      out: qpr
crud:
  create:
    enabled: true
    name: create__NAME__
    params:
      - name: payload
        type: object
  update:
    enabled: true
    name: update__NAME__
    params:
      - name: rid
        type: record
      - name: payload
        type: object
  delete:
    enabled: true
    name: delete__NAME__
    params:
      - name: rid
        type: record
router:
  name: questionPerformanceRecord
  parent: q
  endpoints:
    - create
    - update
    - delete
refreshViews: true
