version: 1
kind: table
name: QuestionRecord
primary: false
tableType: subsingle
description: Question record
table:
  model: qRecord
  type: NORMAL
  schemaMode: schemaless
  permissions: full
structure:
  type: parent
  parentModel: q
id:
  type: string
  exportType: true
  exportName: QuestionRecordId
fields:
  - q:
      type: record<q>
      default: $parent
  - attempts:
      type: number
      default: 0
  - noCorrect:
      type: number
      default: 0
  - noIncorrect:
      type: number
      default: 0
  - percCorrect:
      type: number
      default: 0
edges:
  has: []
  belongs:
    - table: QuestionRecord
      in: q
      out: qRecord
crud:
  create:
    enabled: true
    name: create__NAME__
    params:
      - name: payload
        type: object
  update:
    enabled: true
    name: update__NAME__
    params:
      - name: rid
        type: record
      - name: payload
        type: object
  delete:
    enabled: true
    name: delete__NAME__
    params:
      - name: rid
        type: record
router:
  name: questionRecord
  parent: q
  endpoints:
    - create
    - update
    - delete
refreshViews: true
