version: 1
kind: table
name: UserQuestionNote
primary: false
tableType: submany
description: User notes for questions
table:
  model: uqnote
  type: NORMAL
  schemaMode: schemaless
  permissions: full
id:
  type: string
  exportType: true
  exportName: UserQuestionNoteId
structure:
  type: parent
  parentModel: q
fields:
  - u:
      type: record<u>
      required: true
      default: ""
      assign: true
  - q:
      type: record<q>
      required: true
      default: ""
      assign: true
  - note:
      type: string
      default: ""
  - order:
      type: number
      default: 0
edges:
  has: []
  belongs:
    - table: UserQuestionNote
      in: q
      out: uqnote
crud:
  create:
    enabled: true
    name: create__NAME__
    params:
      - name: payload
        type: object
  update:
    enabled: true
    name: update__NAME__
    params:
      - name: rid
        type: record
      - name: payload
        type: object
  delete:
    enabled: true
    name: delete__NAME__
    params:
      - name: rid
        type: record
router:
  name: userQuestionNote
  parent: q
  endpoints:
    - create
    - update
    - delete
refreshViews: true
