version: 1
kind: table
name: UserQuestionOptionRecord
primary: false
tableType: submany
description: User option performance stats
table:
  model: uqor
  type: NORMAL
  schemaMode: schemaless
  permissions: full
id:
  type: string
  exportType: true
  exportName: UserQuestionOptionRecordId
  structure: stringID<u, qOption>
fields:
  - u:
      type: record<u>
      required: true
      default: ""
      assign: true
  - qOption:
      type: record<qOption>
      required: true
      default: ""
      assign: true
  - attempts:
      type: number
      default: 0
  - correct:
      type: number
      default: 0
  - incorrect:
      type: number
      default: 0
  - percCorrect:
      type: number
      default: 0
  - order:
      type: number
      default: 0
edges:
  has: []
  belongs:
    - table: UserQuestionOptionRecord
      in: qOption
      out: uqor
crud:
  create:
    enabled: true
    name: create__NAME__
    params:
      - name: payload
        type: object
  update:
    enabled: true
    name: update__NAME__
    params:
      - name: rid
        type: record
      - name: payload
        type: object
  delete:
    enabled: true
    name: delete__NAME__
    params:
      - name: rid
        type: record
router:
  name: userQuestionOptionRecord
  parent: qOption
  endpoints:
    - create
    - update
    - delete
refreshViews: true
