name = "MPDG"
grammar = "mpdg"
path_suffixes = ["mpdg", "graph", "graph.mpdg", "graph.txt"]
line_comments = ["// ", "# "]
tab_size = 2
hard_tabs = false
word_characters = ["$", "-"]
autoclose_before = ":\"'}]>)"
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
  { start = "<", end = ">", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false },
  { start = "'", end = "'", close = true, newline = false },
]
