version: 1
kind: table
name: SessionEvent
primary: false
tableType: subsingle
description: Timeline event for a session
table:
  model: se
  type: NORMAL
  schemaMode: schemaless
  permissions: full
id:
  type: string
  exportType: true
  exportName: SessionEventId
structure:
  type: parent
  parentModel: s
fields:
  - action:
      type: string
      required: true
      default: ""
  - time:
      type: datetime
      required: true
      default: ""
  - payload:
      type: object
      ignorePayload: true
  - q:
      type: record<q>
      default: ""
      ignorePayload: true
  - sq:
      type: record<SessionQuestions>
      default: ""
      ignorePayload: true
edges:
  has: []
  belongs:
    - table: SessionEvent
      in: s
      out: se
crud:
  create:
    enabled: true
    name: create__NAME__
    params:
      - name: payload
        type: object
  update:
    enabled: true
    name: update__NAME__
    params:
      - name: rid
        type: record
      - name: payload
        type: object
  delete:
    enabled: true
    name: delete__NAME__
    params:
      - name: rid
        type: record
router:
  name: sessionEvent
  parent: s
  endpoints:
    - create
    - update
    - delete
refreshViews: true
