version: 1
kind: table
name: ExtensionVariant
primary: false
tableType: submany
description: Extension price (days + price)
table:
  model: extensionVariant
  type: NORMAL
  schemaMode: schemaless
  permissions: full
id:
  type: string
  exportType: true
  exportName: ExtensionVariantId
  structure: stringID<productKey, period, currency, numberOfDays>
fields:
  - productKey:
      type: string
      required: true
      default: ""
  - examKey:
      type: string
      required: true
      default: ""
  - product:
      type: record<product>
      required: true
      default: ""
      assign: true
  - exam:
      type: record<exam>
      required: true
      default: ""
      assign: true
  - productVariant:
      type: record<productVariant>
      required: true
      default: ""
      assign: true
  - extensionProduct:
      type: record<extensionProduct>
      required: true
      default: ""
      assign: true
  - period:
      type: int
      required: true
      default: 0
  - currency:
      type: record<currency>
      required: true
      default: ""
      assign: true
  - numberOfDays:
      type: int
      required: true
      default: 0
  - value:
      type: number
      required: true
      default: 0
  - stripePriceID:
      type: string
      default: ""
  - order:
      type: number
      default: 0
edges:
  has: []
  belongs:
    - table: ExtensionVariant
      in: extensionProduct
      out: extensionVariant
crud:
  create:
    enabled: true
    name: create__NAME__
    params:
      - name: payload
        type: object
  update:
    enabled: true
    name: update__NAME__
    params:
      - name: rid
        type: record
      - name: payload
        type: object
  delete:
    enabled: true
    name: delete__NAME__
    params:
      - name: rid
        type: record
router:
  name: extensionVariant
  parent: extensionProduct
  endpoints:
    - create
    - update
    - delete
refreshViews: true
