version: 1
kind: table
name: User
primary: true
tableType: primary
description: Passmed application user
table:
  model: u
  type: NORMAL
  schemaMode: schemaless
  permissions: full
id:
  type: string
  exportType: true
  exportName: UserId
  structure: email
modelSettings:
  authority: tenant
fields:
  - email:
      type: email
      required: true
      default: ""
  - firstName:
      type: string
      required: true
      default: ""
  - surname:
      type: string
      required: true
      default: ""
  - password:
      type: password
      required: true
      default: ""
      options:
        hash: argon2
      assign: true
  - uniqueId:
      type: md5<$email>
      assign: true
  - customerId:
      type: string
      default: ""
  - profile:
      type: subsingle<UserProfile>
      default: ""
      assign: true
  - state:
      type: subsingle<UserState>
      default: ""
      assign: true
  - settings:
      type: subsingle<UserSettings>
      default: ""
      assign: true
  - role:
      type: record<t_u_role>
      required: true
crud:
  create:
    enabled: true
    name: create__NAME__
    params:
      - name: payload
        type: object
  update:
    enabled: true
    name: update__NAME__
    params:
      - name: rid
        type: record
      - name: payload
        type: object
  delete:
    enabled: true
    name: delete__NAME__
    params:
      - name: rid
        type: record
router:
  name: user
  endpoints:
    - create
    - update
    - delete
    - views: "*"
views:
  - name: Admin
    fields:
      - id
      - email
      - firstName
      - surname
      - password
      - uniqueId
      - customerId
      - profile
      - state
      - settings
  - name: Public
    fields:
      - id
      - firstName
      - surname
      - email
      - uniqueId
      - customerId
      - role
    functionMode: generate
    function: viewUserPublic
    as:
      - instances: $instances
    fetch:
      - role
typesense:
  view:
    name: Typesense
    fields:
      - id
      - email
      - firstName
      - surname
      - uniqueId
    functionMode: generate
    function: viewUserTypesense
    as:
      - instances: $instances
  schema:
    collection: user
    fields:
      - name: id
        type: string
      - name: email
        type: string
      - name: firstName
        type: string
      - name: surname
        type: string
      - name: uniqueId
        type: string
      - name: instances
        type: string
        facet: true
    sortableFields:
      - surname
    settings:
      enable_nested_fields: true
  meta:
    settings:
      synonyms: false
      searchAsYouType: false
      perDocumentSynonyms: false
      perDocumentSearchAsYouType: false
      queryBy:
        - email
        - firstName
        - surname
        - uniqueId
        - instances
      queryByWeights:
        - 1
        - 1
        - 1
        - 1
        - 1
      filters:
        - instances
taxonomies:
  - key: role
    labels:
      singular: Role
      plural: Roles
    taxonomy:
      id: stringID<u, role>
      fields:
        - key:
            type: string
            required: true
        - label:
            type: string
            required: true
        - hierarchical:
            type: boolean
            required: false
            default: false
        - permalink:
            type: <permalink<<field:key>>>
            required: false
            assign: true
        - description: User roles
    term:
      id: <field:key>
      fields:
        - key:
            type: string
            required: true
        - label:
            type: string
            required: true
        - description:
            type: string
            required: false
        - parent:
            type: record<term>
            required: false
            default: ""
    hierarchical: false
    cardinality: one
    storeOnModel: true
    payloadField: role
    payloadAliases:
      - roles
    required: true
    processor: functions
instance:
  mode: tenant
post: true
refreshViews: true
admin:
  authority: tenant
  data: tenant
