version: 1
kind: table
name: FAQ
primary: true
tableType: primary
description: Primary FAQ entity representing a single FAQ
table:
  model: faq
  type: NORMAL
  schemaMode: schemaless
  permissions: full
id:
  type: string
  exportType: true
  exportName: FAQId
modelSettings:
  authority: tenant
fields:
  - question:
      type: string
      required: true
      default: ""
  - answer:
      type: string
      required: true
      default: ""
  - category:
      type: string
      required: true
      default: ""
  - faqCategorys:
      type: array
      default: []
  - instances:
      type: array
      required: true
      default: []
crud:
  create:
    enabled: true
    name: create__NAME__
    params:
      - name: payload
        type: object
  update:
    enabled: true
    name: update__NAME__
    params:
      - name: rid
        type: record
      - name: payload
        type: object
  delete:
    enabled: true
    name: delete__NAME__
    params:
      - name: rid
        type: record
router:
  name: fAQ
  endpoints:
    - create
    - update
    - delete
    - views: "*"
views:
  - name: Admin
    fields:
      - id
      - question
      - answer
      - category
      - instances
    as:
      - post: (select status, createdAt, updatedAt from only fn::PID($this.id))
  - name: Public
    fields:
      - id
      - question
      - answer
      - category
      - instances
typesense:
  view:
    name: Typesense
    fields:
      - id
      - question
      - answer
      - category
    functionMode: generate
    function: viewFAQTypesense
    as:
      - instances: $instances
      - post: (select status, createdAt, updatedAt from only fn::PID($this.id))
    __programFieldLists:
      post:
        - status
        - createdAt
        - updatedAt
  schema:
    collection: faq
    fields:
      - name: id
        type: string
      - name: question
        type: string
      - name: answer
        type: string
      - name: category
        type: string
      - name: instances
        type: string[]
        facet: true
      - name: post
        type: object
        fields:
          - name: status
            type: string
          - name: createdAt
            type: string
          - name: updatedAt
            type: string
    sortableFields:
      - question
    settings:
      enable_nested_fields: true
      default_sorting_field: question
  meta:
    settings:
      synonyms: false
      searchAsYouType: false
      perDocumentSynonyms: false
      perDocumentSearchAsYouType: false
      queryBy:
        - question
        - answer
        - category
      queryByWeights:
        - 1
        - 1
        - 1
      filters:
        - instances
    fields:
      post:
        fields: {}
taxonomies:
  - key: faqCategory
    labels:
      singular: Category
      plural: Categories
    taxonomy:
      id: stringID<faq, faqCategory>
      fields:
        - key:
            type: string
            required: true
        - label:
            type: string
            required: true
        - hierarchical:
            type: boolean
            required: false
            default: false
        - permalink:
            type: <permalink<<field:key>>>
            required: false
            assign: true
        - description: FAQ categories
    term:
      id: <field:key>
      fields:
        - key:
            type: string
            required: true
        - label:
            type: string
            required: true
        - description:
            type: string
            required: false
        - parent:
            type: record<term>
            required: false
            default: ""
instance: true
post: true
refreshViews: true
admin:
  authority: tenant
  data: tenant
