DEFINE EVENT OVERWRITE TestimonialPostUpdate ON TABLE testimonial WHEN $event = "UPDATE" THEN { let $RID = $after.id;
if !type::is_record($RID) { throw "TestimonialPostUpdate | invalid record id"; };
let $PID = fn::PID($RID);

if($after.status == "publish" and $before.status != "publish") {
  let $time = time::now();
  fn::updatePost($PID, {
    "updatedAt": $time,
    "publishedAt": $time
  });
} else if $after.status != "publish" {
  fn::updatePost($PID, {
    "updatedAt": time::now(),
    "publishedAt": null
  });
} };